import { afterEach, expect, it } from 'vitest';
import request from 'supertest';
import { app } from '../app.js';
import { env } from '../config/env.js';
import { User, Child, Lesson, Story, ContentDraft, PointTransaction } from '../models/index.js';
import { AuthService } from '../modules/auth/auth.service.js';
import { runSeed } from '../seeds/seed.js';
import { importCustomerContent } from '../seeds/customer/importCustomerContent.js';

afterEach(() => { env.CMS_PUBLISH_ENABLED = false; });
it('imports source drafts, publishes edits, preserves old learning/rewards and survives rename/withdraw/seed reruns', async () => {
  await runSeed();
  const admin = await User.create({ email: 'flow-admin@example.test', passwordHash: 'hash', displayName: 'Admin', role: 'admin' });
  const token = (await AuthService.generateTokens(admin)).accessToken;
  const parent = await AuthService.register({ email: 'flow-parent@example.test', password: 'Password123!', displayName: 'Parent' });
  const child = await Child.create({ parentId: parent.user.id, name: 'An', ageGroup: '5-6', companionLanguage: 'en' });
  const lesson = await Lesson.findOne({ order: 1 }).orFail();
  await Lesson.updateOne({ _id: lesson.id }, { activities: [{ id: 'legacy-q', type: 'review', prompt: 'Choose A', options: [{ id: 'a', text: 'A' }, { id: 'b', text: 'B' }], correctAnswer: 'a' }] });
  const oldAnswers = [{ activityId: 'legacy-q', userAnswer: 'a' }];
  const complete = () => request(app).post(`/api/v1/lessons/${lesson.id}/complete`).set('Authorization', `Bearer ${parent.accessToken}`).send({ childId: child.id, contentVersion: 0, answers: oldAnswers });
  expect((await complete().expect(200)).body.data.pointsEarned).toBe(11); // +10 lesson, +1 passed activity (D1)
  const balance = (await Child.findById(child.id).orFail()).viviPoints;
  await importCustomerContent({ dryRun: false, adminId: admin.id });
  const root = `/api/v1/admin/content/lessons/${lesson.id}`;
  await request(app).get(root).expect(401);
  await request(app).get(root).set('Authorization', `Bearer ${parent.accessToken}`).expect(403);
  await request(app).get(`/api/v1/lessons/${lesson.id}?childId=${child.id}`).set('Authorization', `Bearer ${parent.accessToken}`).expect(200);
  const draft = (await request(app).get(root).set('Authorization', `Bearer ${token}`).expect(200)).body.data.draft;
  expect(draft.source.tabId).toBe('t.6aij8uhnuc6p');
  const payload = { ...draft.payload, vocabulary: [], activities: [{ id: '', type: 'review', prompt: 'Choose B', options: [{ id: 'a', text: 'A' }, { id: 'b', text: 'B' }], correctAnswer: 'b' }] };
  const saved = (await request(app).put(`${root}/draft`).set('Authorization', `Bearer ${token}`).send({ payload, expectedDraftVersion: 1 }).expect(200)).body.data;
  const publish = () => request(app).post(`${root}/publish`).set('Authorization', `Bearer ${token}`).send({ expectedDraftVersion: saved.draftVersion, baseContentVersion: 0 });
  await publish().expect(503);
  env.CMS_PUBLISH_ENABLED = true; await publish().expect(200);
  const replay = await complete().expect(200);
  expect(replay.body.data.scorePercent).toBe(100); expect(replay.body.data.pointsEarned).toBe(0);
  expect((await Child.findById(child.id).orFail()).viviPoints).toBe(balance);
  expect(await PointTransaction.countDocuments({ childId: child.id, reason: 'lesson' })).toBe(1);
  await request(app).put(`/api/v1/admin/lessons/${lesson.id}`).set('Authorization', `Bearer ${token}`).send({ title: 'Forbidden direct edit' }).expect(409);
  const storyDraft = await ContentDraft.findOne({ requestId: /^customer:story-02:/ }).orFail();
  const storyRoot = `/api/v1/admin/content/stories/${storyDraft.contentId}`;
  await request(app).post(`${storyRoot}/publish`).set('Authorization', `Bearer ${token}`).send({ expectedDraftVersion: 1, baseContentVersion: 0 }).expect(200);
  const story = (await request(app).get(`/api/v1/stories/${storyDraft.contentId}`).expect(200)).body.data;
  expect(story.lyrics[1].text).toBe('Có cây xúc sắc'); expect(story.source).toBeUndefined();
  const reopened = (await request(app).post(`${storyRoot}/draft`).set('Authorization', `Bearer ${token}`).send({ expectedDraftVersion: 2 }).expect(200)).body.data;
  const renamed = (await request(app).put(`${storyRoot}/draft`).set('Authorization', `Bearer ${token}`).send({ payload: { ...reopened.payload, title: 'Tên biên tập mới' }, expectedDraftVersion: reopened.draftVersion }).expect(200)).body.data;
  await request(app).post(`${storyRoot}/publish`).set('Authorization', `Bearer ${token}`).send({ expectedDraftVersion: renamed.draftVersion, baseContentVersion: 1 }).expect(200);
  await request(app).patch(`${storyRoot}/visibility`).set('Authorization', `Bearer ${token}`).send({ visibility: 'withdrawn', expectedContentVersion: 2 }).expect(200);
  await runSeed(); const rerun = await importCustomerContent({ dryRun: false, adminId: admin.id });
  expect(rerun.entries.every(entry => entry.action === 'skip')).toBe(true); expect(await Story.countDocuments()).toBe(21);
  await request(app).get(`/api/v1/stories/${storyDraft.contentId}`).expect(404);
  expect((await Story.findById(storyDraft.contentId).orFail()).title).toBe('Tên biên tập mới');
});
it('keeps legacy content readable and editable when it exceeds new draft constraints', async () => {
  await runSeed();
  const admin = await User.create({ email: 'legacy-admin@example.test', passwordHash: 'hash', displayName: 'Admin', role: 'admin' });
  const token = (await AuthService.generateTokens(admin)).accessToken;
  const lesson = await Lesson.findOne({ order: 20 }).orFail();
  await Lesson.updateOne({ _id: lesson.id }, { order: 28 });
  const result = await request(app).get(`/api/v1/admin/content/lessons/${lesson.id}`).set('Authorization', `Bearer ${token}`).expect(200);
  expect(result.body.data.live.payload.order).toBe(28);
  const story = await Story.findOne().orFail();
  await Story.updateOne({ _id: story.id }, { audioUrl: 'http://legacy.example.test/audio.mp3' });
  const publicStory = await request(app).get(`/api/v1/stories/${story.id}`).expect(200);
  expect(publicStory.body.data.audioUrl).toBe('http://legacy.example.test/audio.mp3');
  const draft = (await request(app).post(`/api/v1/admin/content/lessons/${lesson.id}/draft`).set('Authorization', `Bearer ${token}`).send({}).expect(200)).body.data;
  await request(app).put(`/api/v1/admin/content/lessons/${lesson.id}/draft`).set('Authorization', `Bearer ${token}`).send({ payload: { ...draft.payload, title: 'Catalog cũ vẫn biên tập được' }, expectedDraftVersion: draft.draftVersion }).expect(200);
});
