/**
 * Ảnh bìa minh họa demo cho story/culture, tự host tại client/public/images/covers.
 * Nguồn: Wikimedia Commons (Public domain, CC0, CC BY, CC BY-SA). Ảnh đã được cắt/thu nhỏ về 800x600.
 * CC BY/BY-SA bắt buộc ghi công: xem docs/content-image-credits.md.
 * Giả định: đây là ảnh demo, content team phải duyệt lại trước production.
 * Dùng bởi applyContentCovers.ts; seedKey/title khớp server/src/seeds/catalog.ts.
 */
export type ContentCover = {
  kind: 'story' | 'culture';
  seedKey: string;
  title: string;
  coverImage: string;
  /** Trang File: trên Wikimedia Commons. */
  sourceUrl: string;
  author: string;
  license: string;
  licenseUrl: string;
};

export const contentCovers: ContentCover[] = [
  { kind: 'story', seedKey: 'story-01', title: 'Trồng nụ trồng hoa',
    coverImage: '/images/covers/stories/trong-nu-trong-hoa.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Waterlily_(8677125409).jpg',
    author: 'Clumsyninja', license: 'CC BY 4.0', licenseUrl: 'https://creativecommons.org/licenses/by/4.0' },
  { kind: 'story', seedKey: 'story-02', title: 'Rồng rắn lên mây',
    coverImage: '/images/covers/stories/rong-ran-len-may.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tranh_v%E1%BA%BD_c%E1%BA%A3nh_m%C3%BAa_r%E1%BB%93ng_trong_m%E1%BB%99t_l%E1%BB%85_h%E1%BB%99i_th%E1%BB%9Di_Nguy%E1%BB%85n.jpg',
    author: 'Vietnamese artist', license: 'Public domain', licenseUrl: 'https://commons.wikimedia.org/wiki/File:Tranh_v%E1%BA%BD_c%E1%BA%A3nh_m%C3%BAa_r%E1%BB%93ng_trong_m%E1%BB%99t_l%E1%BB%85_h%E1%BB%99i_th%E1%BB%9Di_Nguy%E1%BB%85n.jpg' },
  { kind: 'story', seedKey: 'story-03', title: 'Hai bàn tay',
    coverImage: '/images/covers/stories/hai-ban-tay.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Child_washing_hands_closeup.jpg',
    author: 'Shixart1985', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0' },
  { kind: 'story', seedKey: 'story-04', title: 'Dung dăng dung dẻ',
    coverImage: '/images/covers/stories/dung-dang-dung-de.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Children_hold_hands_in_a_bright_room_filled_with_toys_during_a_playtime_moment.jpg',
    author: 'Shixart1985', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0' },
  { kind: 'story', seedKey: 'story-05', title: 'Nu na nu nống',
    coverImage: '/images/covers/stories/nu-na-nu-nong.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kindergarten_in_VN.jpg',
    author: 'HD', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  { kind: 'story', seedKey: 'story-06', title: 'Lộn cầu vồng',
    coverImage: '/images/covers/stories/lon-cau-vong.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:C%E1%BA%A7u_v%E1%BB%93ng_h%C3%A0_n%E1%BB%99i.jpg',
    author: 'Jspeed1310 at Vietnamese Wikipedia', license: 'Public domain', licenseUrl: 'https://commons.wikimedia.org/wiki/File:C%E1%BA%A7u_v%E1%BB%93ng_h%C3%A0_n%E1%BB%99i.jpg' },
  { kind: 'story', seedKey: 'story-07', title: 'Cái ngủ mày ngủ cho lâu',
    coverImage: '/images/covers/stories/cai-ngu-may-ngu-cho-lau.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Sleeping_baby_(6410829477).jpg',
    author: 'Toshiyuki IMAI from Kyoto, Japan', license: 'CC BY-SA 2.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0' },
  { kind: 'story', seedKey: 'story-08', title: 'Gánh gánh gồng gồng',
    coverImage: '/images/covers/stories/ganh-ganh-gong-gong.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Une_marchande_de_l%C3%A9gumes_(Hu%C3%A9)_(4379322465).jpg',
    author: 'dalbera from Paris, France', license: 'CC BY 2.0', licenseUrl: 'https://creativecommons.org/licenses/by/2.0' },
  { kind: 'story', seedKey: 'story-09', title: 'Con công hay múa',
    coverImage: '/images/covers/stories/con-cong-hay-mua.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Paonroue.JPG',
    author: 'Jebulon', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  { kind: 'story', seedKey: 'story-10', title: 'Rềnh rềnh ràng ràng',
    coverImage: '/images/covers/stories/renh-renh-rang-rang.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tr%E1%BB%91ng_c%C6%A1m_-_55cm.jpg',
    author: 'Trúc Đồng', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  { kind: 'story', seedKey: 'story-11', title: 'Con cua mà có hai càng',
    coverImage: '/images/covers/stories/con-cua-ma-co-hai-cang.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:SAND_CRAB_MONKEY_ISLAND_NHA_TRANG_BAY_VIETNAM_JAN_2012_(6821793914).jpg',
    author: 'calflier001', license: 'CC BY-SA 2.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.0' },
  { kind: 'story', seedKey: 'story-12', title: 'Lúa ngô là cô đậu nành',
    coverImage: '/images/covers/stories/lua-ngo-la-co-dau-nanh.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Rice_Field_in_Vietnam_-_panoramio.jpg',
    author: 'Gonzo Gooner', license: 'CC BY 3.0', licenseUrl: 'https://creativecommons.org/licenses/by/3.0' },
  { kind: 'story', seedKey: 'story-13', title: 'Kéo cưa lừa xẻ',
    coverImage: '/images/covers/stories/keo-cua-lua-xe.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Two-man_saw_used_by_carpenters_to_saw_planks_from_a_tree_trunk_by_hand_Dhading_Nepal_24Apr2008.jpg',
    author: 'Everhard van Eimeren', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  { kind: 'story', seedKey: 'story-14', title: 'Chi chi chành chành',
    coverImage: '/images/covers/stories/chi-chi-chanh-chanh.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:B%E1%BB%8Bt_m%E1%BA%AFt_%C4%91%E1%BA%ADp_ni%C3%AAu_2.JPG',
    author: 'LÊ TẤN LỘC', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  { kind: 'story', seedKey: 'story-15', title: 'Ông sảo ông sao',
    coverImage: '/images/covers/stories/ong-sao-ong-sao.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Night_Sky_-_Boney_Mountain_%26_Milky_Way_(11074300594).jpg',
    author: 'Santa Monica Mountains National Recreation Area', license: 'Public domain', licenseUrl: 'https://commons.wikimedia.org/wiki/File:Night_Sky_-_Boney_Mountain_%26_Milky_Way_(11074300594).jpg' },
  { kind: 'story', seedKey: 'story-16', title: 'Ông giẳng ông giăng',
    coverImage: '/images/covers/stories/ong-giang-ong-giang.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Full_moon_in_the_evening_in_the_dry_paddy_fields_of_Don_Det_Laos.jpg',
    author: 'Basile Morin', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  { kind: 'story', seedKey: 'story-17', title: 'Chú Cuội ngồi gốc cây đa',
    coverImage: '/images/covers/stories/chu-cuoi-ngoi-goc-cay-da.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:C%C3%A2y_%C4%91a_%C4%90%C3%B4ng_%C4%90%E1%BB%91ng.jpg',
    author: 'Nguyentaithuyen', license: 'Public domain', licenseUrl: 'https://commons.wikimedia.org/wiki/File:C%C3%A2y_%C4%91a_%C4%90%C3%B4ng_%C4%90%E1%BB%91ng.jpg' },
  { kind: 'story', seedKey: 'story-18', title: 'Bà còng đi chợ trời mưa',
    coverImage: '/images/covers/stories/ba-cong-di-cho-troi-mua.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:%E3%82%B7%E3%83%A7%E3%82%AD%E3%82%BF%E3%83%86%E3%83%8A%E3%82%AC%E3%82%A8%E3%83%93.jpg',
    author: 'Ffish.asia', license: 'CC BY 4.0', licenseUrl: 'https://creativecommons.org/licenses/by/4.0' },
  { kind: 'story', seedKey: 'story-19', title: 'Cái bống là cái bống bang',
    coverImage: '/images/covers/stories/cai-bong-la-cai-bong-bang.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Glossogobius_giuris.jpg',
    author: 'Trevor Menezes', license: 'CC BY 3.0', licenseUrl: 'https://creativecommons.org/licenses/by/3.0' },
  { kind: 'story', seedKey: 'story-20', title: 'Thằng Bờm có cái quạt mo',
    coverImage: '/images/covers/stories/thang-bom-co-cai-quat-mo.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Woven_palm_leaf_fan.jpg',
    author: 'Codobai', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  { kind: 'story', seedKey: 'story-21', title: 'Nhạc rừng',
    coverImage: '/images/covers/stories/nhac-rung.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Khung_c%E1%BA%A3nh_thi%C3%AAn_nhi%C3%AAn_t%C6%B0%C6%A1i_%C4%91%E1%BA%B9p_b%C3%AAn_trong_V%C6%B0%E1%BB%9Dn_Qu%E1%BB%91c_gia_C%C3%BAc_Ph%C6%B0%C6%A1ng_t%E1%BA%A1i_Ninh_B%C3%ACnh,_Vi%E1%BB%87t_Nam.jpg',
    author: 'Peter Jackal', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  { kind: 'culture', seedKey: 'culture-tet', title: 'Tết và lời chúc đầu năm',
    coverImage: '/images/covers/culture/tet-loi-chuc-dau-nam.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Hoa_%C4%91%C3%A0o.JPG',
    author: 'Casablanca1911 at vi.wikipedia', license: 'Public domain', licenseUrl: 'https://commons.wikimedia.org/wiki/File:Hoa_%C4%91%C3%A0o.JPG' },
  { kind: 'culture', seedKey: 'culture-am_thuc', title: 'Món ăn từ hạt gạo',
    coverImage: '/images/covers/culture/mon-an-tu-hat-gao.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Nguyen_lieu_banh_chung.jpg',
    author: 'vi:user:Viethavvh', license: 'Public domain', licenseUrl: 'https://commons.wikimedia.org/wiki/File:Nguyen_lieu_banh_chung.jpg' },
  { kind: 'culture', seedKey: 'culture-trang_phuc', title: 'Áo dài và trang phục Việt',
    coverImage: '/images/covers/culture/ao-dai-trang-phuc-viet.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:%C3%81o_d%C3%A0i_b%C3%A9_trai_thi%E1%BA%BFt_k%E1%BA%BF_Nhi%C3%AAn_Kids.jpg',
    author: 'Nhiên Kids', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  { kind: 'culture', seedKey: 'culture-phong_tuc', title: 'Lời chào trong gia đình',
    coverImage: '/images/covers/culture/loi-chao-trong-gia-dinh.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Vietnamese_family_daily_meal.jpg',
    author: 'Hoangkid', license: 'CC BY-SA 4.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0' },
  { kind: 'culture', seedKey: 'culture-le_hoi', title: 'Đêm hội Trung thu',
    coverImage: '/images/covers/culture/dem-hoi-trung-thu.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Mid-Autumn_Star_DN.JPG',
    author: 'Dragfyre', license: 'CC BY-SA 3.0', licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0' },
  { kind: 'culture', seedKey: 'culture-vat_dung', title: 'Nón lá và trống đồng',
    coverImage: '/images/covers/culture/non-la-va-trong-dong.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Tan_Do_Bronze_Drum_a.jpg',
    author: 'Gary Todd', license: 'CC0', licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en' },
  { kind: 'culture', seedKey: 'culture-thien_nhien', title: 'Thiên nhiên Việt Nam',
    coverImage: '/images/covers/culture/thien-nhien-viet-nam.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Road_and_paddy_fields_in_Sa_Pa,_Vietnam,_20240126_1203_3590.jpg',
    author: 'Jakub Hałun', license: 'CC BY 4.0', licenseUrl: 'https://creativecommons.org/licenses/by/4.0' },
  { kind: 'culture', seedKey: 'culture-tro_choi_dan_gian', title: 'Cùng chơi trò dân gian',
    coverImage: '/images/covers/culture/cung-choi-tro-dan-gian.jpg',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Ch%C6%A1i_%C3%B4_%C4%83n_quan_(Tr%C6%B0%E1%BB%9Dng_Sa).jpg',
    author: 'Phạm Xuân Nguyên', license: 'CC BY 3.0', licenseUrl: 'https://creativecommons.org/licenses/by/3.0' },
];
